; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_famidash_music6=music_data_famidash_music6
.endif

music_data_famidash_music6:
	.byte 2
	.word @instruments
	.word @samples-4
; 00 : custom_atthespeedoflight
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 331,276

.export music_data_famidash_music6
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env16,@env4,@env22,@env0 ; 00 : rel hats
	.word @env20,@env23,@env22,@env0 ; 01 : clap
	.word @env17,@env21,@env2,@env0 ; 02 : snare
	.word @env31,@env19,@env22,@env0 ; 03 : tight noise kick layer
	.word @env11,@env19,@env15,@env0 ; 04 : hex guitar 2
	.word @env10,@env19,@env12,@env0 ; 05 : polargeist bass
	.word @env7,@env29,@env22,@env0 ; 06 : kick
	.word @env26,@env19,@env22,@env27 ; 07 : jaezu lead
	.word @env14,@env19,@env22,@env0 ; 08 : blank
	.word @env18,@env19,@env22,@env0 ; 09 : blank string
	.word @env1,@env19,@env22,@env0 ; 0a : echo
	.word @env30,@env4,@env2,@env0 ; 0b : cymbal
	.word @env8,@env9,@env5,@env0 ; 0c : Instrument 3
	.word @env11,@env19,@env22,@env0 ; 0d : DMC: drums + bass
	.word @env3,@env19,@env22,@env13 ; 0e : triangle drums
	.word @env28,@env19,@env22,@env0 ; 0f : triangle pluck 4
	.word @env6,@env19,@env22,@env0 ; 10 : clutterfunk sax
	.word @env25,@env33,@env24,@env0 ; 11 : octave arp

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cb,$c7,$c5,$c4,$c3,$c2,$c2,$c1,$c1,$c0,$c5,$c4,$c3,$c3,$c2,$c2,$c1,$c1,$c0,$00,$13
@env2:
	.byte $c1,$c0,$00,$01
@env3:
	.byte $00,$c9,$c8,$c7,$c6,$c6,$c5,$c5,$c4,$00,$08
@env4:
	.byte $bd,$c0,$00,$01
@env5:
	.byte $c2,$c1,$c0,$c1,$00,$02
@env6:
	.byte $05,$ce,$cf,$00,$02,$cc,$c8,$c5,$c2,$c0,$00,$09
@env7:
	.byte $00,$cd,$c9,$c5,$c2,$c1,$c0,$00,$06
@env8:
	.byte $00,$ca,$cf,$02,$ce,$cd,$cc,$ca,$c8,$c6,$c3,$00,$0a
@env9:
	.byte $b4,$c0,$00,$01
@env10:
	.byte $00,$cf,$cd,$cb,$c7,$c7,$ca,$00,$06
@env11:
	.byte $00,$cf,$7f,$00,$02
@env12:
	.byte $c3,$c2,$c2,$c1,$00,$03
@env13:
	.byte $80,$bf,$f1,$00,$02
@env14:
	.byte $04,$cf,$00,$01,$ca,$c6,$c4,$c2,$c0,$00,$08
@env15:
	.byte $c3,$c2,$c1,$c3,$00,$03
@env16:
	.byte $00,$c8,$c6,$c5,$c5,$c4,$c4,$c3,$02,$c2,$02,$c1,$02,$c0,$00,$0d
@env17:
	.byte $00,$cd,$cb,$c8,$c6,$c5,$c4,$c3,$c2,$c1,$c1,$c0,$00,$0b
@env18:
	.byte $08,$c5,$c6,$c7,$08,$c6,$00,$05,$c6,$c6,$c5,$02,$c4,$02,$c3,$02,$c2,$02,$c1,$c1,$c0,$00,$14
@env19:
	.byte $c0,$7f,$00,$01
@env20:
	.byte $00,$cf,$ca,$cc,$ca,$c9,$c8,$c6,$c5,$c4,$c2,$c1,$c0,$00,$0c
@env21:
	.byte $c6,$cc,$00,$01
@env22:
	.byte $7f,$00,$00
@env23:
	.byte $bc,$c1,$c0,$00,$02
@env24:
	.byte $c2,$7f,$00,$00
@env25:
	.byte $00,$c9,$c7,$c5,$00,$03
@env26:
	.byte $0d,$c6,$c8,$ca,$cc,$03,$cb,$03,$ca,$03,$c9,$00,$0a,$c8,$c7,$c7,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$02,$c2,$02,$c1,$02,$c0,$00,$1c
@env27:
	.byte $00,$c0,$07,$c0,$c1,$c2,$c3,$c2,$c1,$c0,$bf,$be,$bd,$be,$bf,$00,$03
@env28:
	.byte $00,$cf,$03,$c0,$00,$03
@env29:
	.byte $c9,$cf,$00,$01
@env30:
	.byte $18,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c8,$c7,$c7,$c6,$02,$c5,$c5,$c4,$02,$c3,$03,$c2,$c2,$00,$15,$c2,$c2,$c1,$03,$c0,$00,$1c
@env31:
	.byte $00,$cf,$c0,$c1,$c0,$00,$04
@env32:
	.byte $c0,$c3,$c0,$00,$00
@env33:
	.byte $c0,$c0,$cc,$cc,$00,$00
@env34:
	.byte $c0,$c5,$cf,$00,$00

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0f,$40 ; 00 fdbass A# (Pitch:15)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0d,$40 ; 01 fdbass B (Pitch:13)
	.byte $12+.lobyte(FAMISTUDIO_DPCM_PTR),$45,$0f,$40 ; 02 fdbass B (Pitch:15)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$07,$40 ; 03 fdbass C (Pitch:7)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$09,$40 ; 04 fdbass C (Pitch:9)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0a,$40 ; 05 fdbass C (Pitch:10)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0c,$40 ; 06 fdbass C (Pitch:12)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0e,$40 ; 07 fdbass C (Pitch:14)
	.byte $24+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0f,$40 ; 08 fdbass C (Pitch:15)
	.byte $36+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$05,$40 ; 09 fdbass C# (Pitch:5)
	.byte $36+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$07,$40 ; 0a fdbass C# (Pitch:7)
	.byte $36+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$08,$40 ; 0b fdbass C# (Pitch:8)
	.byte $36+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0a,$40 ; 0c fdbass C# (Pitch:10)
	.byte $36+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0b,$40 ; 0d fdbass C# (Pitch:11)
	.byte $36+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0c,$40 ; 0e fdbass C# (Pitch:12)
	.byte $36+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0d,$40 ; 0f fdbass C# (Pitch:13)
	.byte $36+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0e,$40 ; 10 fdbass C# (Pitch:14)
	.byte $36+.lobyte(FAMISTUDIO_DPCM_PTR),$47,$0f,$40 ; 11 fdbass C# (Pitch:15)
	.byte $48+.lobyte(FAMISTUDIO_DPCM_PTR),$46,$07,$40 ; 12 fdbass D (Pitch:7)
	.byte $48+.lobyte(FAMISTUDIO_DPCM_PTR),$46,$08,$40 ; 13 fdbass D (Pitch:8)
	.byte $48+.lobyte(FAMISTUDIO_DPCM_PTR),$46,$0a,$40 ; 14 fdbass D (Pitch:10)
	.byte $48+.lobyte(FAMISTUDIO_DPCM_PTR),$46,$0b,$40 ; 15 fdbass D (Pitch:11)
	.byte $48+.lobyte(FAMISTUDIO_DPCM_PTR),$46,$0c,$40 ; 16 fdbass D (Pitch:12)
	.byte $48+.lobyte(FAMISTUDIO_DPCM_PTR),$46,$0f,$40 ; 17 fdbass D (Pitch:15)
	.byte $a2+.lobyte(FAMISTUDIO_DPCM_PTR),$2b,$0e,$40 ; 18 fdkick (Pitch:14)
	.byte $69+.lobyte(FAMISTUDIO_DPCM_PTR),$38,$0f,$40 ; 19 is a (Pitch:15)
	.byte $86+.lobyte(FAMISTUDIO_DPCM_PTR),$6d,$0f,$40 ; 1a machine (Pitch:15)
	.byte $ad+.lobyte(FAMISTUDIO_DPCM_PTR),$41,$0f,$40 ; 1b snare (Pitch:15)
	.byte $5a+.lobyte(FAMISTUDIO_DPCM_PTR),$39,$0f,$40 ; 1c this (Pitch:15)
	.byte $78+.lobyte(FAMISTUDIO_DPCM_PTR),$37,$0f,$40 ; 1d time (Pitch:15)

@song0ch0:
	.byte $46, $06, $a2, $0d, $ad, $09, $85, $0b, $85, $0d, $9d, $0b, $9d, $78, $98
@song0ref16:
	.byte $31, $2d, $2a, $25, $1e, $20, $21, $25, $31, $2d, $2a, $25, $1e, $20, $21, $25, $1e, $20, $21, $25, $20, $21, $25, $2a
	.byte $21, $25, $2a, $2d, $25, $2a, $2d, $2f, $31, $2d, $2a, $2d, $26, $2a, $21, $26, $1e, $15, $1a, $1e, $15, $1a, $1e, $20
	.byte $2d, $2c, $2a, $26, $2a, $2c, $2d, $32, $36, $34, $32, $2d, $32, $34, $36, $39
	.byte $41, $40
	.word @song0ref16
	.byte $8a, $2c, $88, $2c, $00, $85, $8a, $2d, $88, $2d, $00, $85, $8a, $2c, $88, $2c, $00, $85, $8a, $2f, $88, $2f, $00, $85
	.byte $8a, $2d, $88, $2d, $00, $81, $8a, $2c, $88, $2c, $00, $81, $8a, $2d, $88, $2d, $00, $85, $8a, $34, $88, $34, $00, $85
	.byte $8a, $33, $88, $33, $00, $85, $8a, $2f, $88, $2f, $00, $85, $8a, $33, $88, $33, $00, $81, $8a, $34, $88, $34, $00, $81
	.byte $8a, $2f, $88, $2f, $00, $85, $8a, $2d, $88, $2d, $00, $85, $8a, $2c, $88, $2c, $00, $85, $8a, $2d, $88, $2d, $00, $85
	.byte $8a, $2c, $88, $2c, $00, $81, $8a, $28, $88, $28, $00, $81, $94
@song0ref192:
	.byte $24, $1c, $20, $24, $27, $20, $2a, $27, $2a, $27, $2c, $2a, $2a, $27, $30, $2c, $30, $38, $33, $3c, $30, $2c, $33, $30
	.byte $38, $36, $34, $33, $36, $34, $33, $34, $76, $4e, $ff, $90
@song0ref228:
	.byte $28, $81, $20, $81, $25, $81, $27, $81, $28, $81, $20, $81, $25, $81, $28, $81, $27, $81, $1e, $81, $23
@song0ref249:
	.byte $81, $25, $85, $1c, $81, $23, $81, $21, $81, $23, $81, $17, $81, $1c, $81, $17, $81, $1c, $81, $1e, $81, $20, $81, $17
	.byte $81, $21, $81, $19, $81, $1e, $81, $20, $85, $19, $81, $1b, $81, $1c, $81
	.byte $41, $14
	.word @song0ref228
	.byte $2c
	.byte $41, $1f
	.word @song0ref249
	.byte $25, $85, $28, $81, $27, $81, $25, $81, $4e, $ff
	.byte $41, $3c
	.word @song0ref228
	.byte $41, $14
	.word @song0ref228
	.byte $2c
	.byte $41, $1f
	.word @song0ref249
@song0ref315:
	.byte $25, $85, $28, $81, $27, $81, $25
@song0ref322:
	.byte $81, $2a, $81, $22, $81, $27, $81, $29, $81, $2a, $81, $22, $81, $27, $81, $2a, $81, $29, $81, $20, $81, $25
@song0ref344:
	.byte $81, $27, $85, $1e, $81, $25, $81, $23, $81, $25, $81, $19, $81, $1e, $81, $19, $81, $1e, $81, $20, $81, $22, $81, $19
	.byte $81, $23, $81, $1b, $81, $20, $81, $22, $85, $1b, $81, $1d, $81, $1e
	.byte $41, $13
	.word @song0ref322
	.byte $22, $81, $2e
	.byte $41, $1f
	.word @song0ref344
	.byte $27, $85, $2a, $81, $29, $81, $27
	.byte $41, $3c
	.word @song0ref322
	.byte $41, $13
	.word @song0ref322
	.byte $22, $81, $2e
	.byte $41, $1f
	.word @song0ref344
	.byte $27, $85, $2a, $81, $29, $81, $27, $81, $7f, $4e, $00
@song0ref421:
	.byte $94, $2a, $27, $24, $21, $1e, $1b, $1e, $1b, $18, $1b, $18, $15, $1e, $1b, $18, $21, $20, $22, $24, $27, $24, $27, $2a
	.byte $2d, $2c, $85, $00, $85, $7b
@song0ref451:
	.byte $4e, $ff, $00
@song0ref454:
	.byte $4f, $01, $25, $20, $1c, $19, $20, $1c, $19, $14, $1c, $81, $19, $1c, $14, $19, $1c, $81, $23, $20, $1c, $17, $21, $1c
	.byte $17, $81, $10, $12, $15, $19, $12, $15, $19, $1e, $83, $19, $1c, $14, $19, $1e, $14, $19, $1b, $14, $19, $1c, $1b, $19
	.byte $14, $20, $81, $19, $1c, $14, $19, $1e, $14, $19, $1b, $14, $1b, $1c, $1b, $1c, $1e, $28, $25, $21, $1c, $25, $21, $1c
	.byte $19, $15, $19, $1c, $21, $1c, $21, $28, $2a, $2d, $2a, $25, $21, $2a, $25, $21, $1e, $19, $1e, $21, $25, $1e, $21, $25
	.byte $00, $81
@song0ref552:
	.byte $14, $20, $27, $19, $20, $25, $19, $20, $28, $19, $20, $27, $28, $27, $23, $25, $19, $23, $25, $19, $1c, $20, $1c, $1e
	.byte $1c, $1e, $20, $21, $20, $21
	.byte $41, $60
	.word @song0ref451
@song0ref585:
	.byte $2c, $2d, $2b, $2a, $28, $2a, $28, $27, $23, $28, $2c, $2f, $2c, $28, $27, $28, $27, $2a, $27, $24, $20, $24, $20, $1b
	.byte $18, $1b, $20, $24, $20, $27, $2c, $4e, $00, $8e, $31, $95, $92, $28, $89, $2c, $89, $31, $81, $2c, $81, $31, $81, $33
	.byte $81, $4e, $00, $34, $81, $33, $81, $2f, $81, $2a, $81, $28, $81, $27, $81, $23, $81, $8e, $1e, $85, $92, $23, $81, $2c
	.byte $81, $28, $81, $27, $81, $28, $81, $2f, $31, $2f, $81, $28, $81, $20, $81, $25, $81, $27, $81, $20, $81, $25, $81, $28
	.byte $81, $20, $81, $25, $81, $2c, $81, $25, $81, $28, $81, $31, $81, $28, $81, $31, $81, $33, $81, $34, $81, $28, $81, $31
	.byte $81, $8e, $38, $85, $36, $85, $33, $85, $92, $2a, $81, $31, $81, $33, $81, $34, $85, $33, $85, $8e, $31, $8d, $45, $85
	.byte $44, $00
@song0ch1:
	.byte $4f, $02, $94, $2c, $28, $25, $28, $20, $25, $1c, $20, $19, $20, $1c, $20, $25, $2c, $2a, $28, $7b, $4f, $02, $2c, $28
	.byte $25, $28, $20, $25, $78, $1c, $20, $19, $20, $1c, $75, $20, $25, $2c, $2a, $28, $00, $bd, $7a, $98
@song0ref776:
	.byte $12, $85, $00, $85, $12, $85, $00, $85, $12, $85, $00, $81, $12, $81, $12, $81, $12, $81, $12, $81, $12, $81, $0e, $85
	.byte $0e, $81, $0e, $85, $0e, $81, $0e, $85, $0e, $81, $0e, $85, $0e, $81, $0e, $81, $0e, $81, $0e, $81, $0e, $81
	.byte $41, $2e
	.word @song0ref776
	.byte $79, $00, $94
@song0ref828:
	.byte $25, $27, $28, $27, $25, $25, $25, $27, $28, $27, $25, $25
	.byte $41, $0c
	.word @song0ref828
	.byte $25, $27, $28, $28, $28, $27, $25
@song0ref850:
	.byte $21, $21, $25, $28, $25, $21, $21, $21, $25, $28, $25, $21
	.byte $41, $0c
	.word @song0ref850
	.byte $21, $21, $25, $28, $28, $28, $25, $21
@song0ref873:
	.byte $20, $23, $28, $23, $20, $20, $20, $23, $28, $23, $20, $20
	.byte $41, $0c
	.word @song0ref873
	.byte $20, $23, $28, $28, $28, $23, $20, $20, $20, $18, $1c, $18, $24, $24, $27, $24, $27, $24, $2a, $00, $2c, $2a, $38, $30
	.byte $3c, $30, $38, $30, $33, $30, $38, $33, $00, $8d, $76, $88
	.byte $41, $3c
	.word @song0ref228
	.byte $41, $14
	.word @song0ref228
	.byte $2c
	.byte $41, $1f
	.word @song0ref249
	.byte $25, $85, $28, $81, $27, $81, $25, $81
	.byte $41, $3c
	.word @song0ref228
	.byte $41, $14
	.word @song0ref228
	.byte $2c
	.byte $41, $1f
	.word @song0ref249
	.byte $41, $43
	.word @song0ref315
	.byte $41, $13
	.word @song0ref322
	.byte $22, $81, $2e
	.byte $41, $1f
	.word @song0ref344
	.byte $27, $85, $2a, $81, $29, $81, $27
	.byte $41, $3c
	.word @song0ref322
	.byte $41, $13
	.word @song0ref322
	.byte $22, $81, $2e
	.byte $41, $1f
	.word @song0ref344
	.byte $27, $85, $2a, $81, $29, $81, $27, $81, $00, $7f
	.byte $41, $1b
	.word @song0ref421
	.byte $83
	.byte $41, $5e
	.word @song0ref454
	.byte $2a, $00
	.byte $41, $1e
	.word @song0ref552
	.byte $23
	.byte $41, $5e
	.word @song0ref454
	.byte $2a
	.byte $41, $1f
	.word @song0ref585
	.byte $30, $78, $00, $89, $92, $1b, $81, $1c, $81, $20, $81, $25, $89, $27, $89, $23, $8d, $4e, $00, $15, $81, $1c, $81, $21
	.byte $81, $25, $81, $28, $81, $2c, $81, $8e, $2d, $85, $92, $23, $81, $1e, $81, $23, $85, $27, $85, $2f, $85
@song0ref1058:
	.byte $28, $89, $27, $89, $23, $89, $28, $89, $27, $85, $23, $85, $15, $81, $17, $81, $1c, $81, $21, $81, $23, $81, $25, $81
	.byte $2c, $81, $8e, $2d, $85, $92, $27, $81, $2c, $81, $2e, $81, $2f, $85, $2e, $85, $8e, $2c, $8f, $45, $83, $44, $00
@song0ch2:
	.byte $81, $7a, $81, $98
@song0ref1110:
	.byte $0d, $81, $00, $81, $0d, $81, $00, $81, $0d, $81, $00, $81, $0d, $81, $00, $81, $0d, $81, $00, $81, $0d, $81, $10, $10
	.byte $10, $10, $10, $10, $10, $10, $07, $87, $00, $07, $87, $00, $07, $87, $00, $05, $87, $00, $05, $05, $05, $05, $05, $05
	.byte $05, $05, $00, $bd, $bf, $bf, $bf, $9c
@song0ref1166:
	.byte $19, $85, $19, $85, $19, $85, $19, $85, $19, $85, $19, $85
	.byte $41, $0c
	.word @song0ref1166
	.byte $41, $0c
	.word @song0ref1166
	.byte $41, $0c
	.word @song0ref1166
	.byte $9e
	.byte $41, $20
	.word @song0ref192
	.byte $75, $90, $50, $04, $55, $25, $bd, $a7, $00, $95, $72, $92, $25, $9d, $27, $89, $28, $91, $20, $9d, $21, $85, $1e, $81
	.byte $1c, $89, $4b, .lobyte(@env32), .hibyte(@env32), $90, $50, $f4, $34, $46, $85, $4b, .lobyte(@env19), .hibyte(@env19)
	.byte $4c, $92, $25, $9d, $27, $89, $28, $91, $23, $9d, $21, $85, $20, $95, $7f, $a0, $31, $9d, $33, $89, $34, $91, $2c, $9d
	.byte $2d, $89, $31, $89, $4b, .lobyte(@env34), .hibyte(@env34), $90, $50, $e7, $2a, $43, $85
@song0ref1266:
	.byte $4b, .lobyte(@env19), .hibyte(@env19), $4c, $9a, $33, $9d, $35, $89, $36, $91, $31, $9d, $2f, $89, $2e, $91, $33, $9d
	.byte $35, $89, $36, $91, $2e, $9d, $2f, $85, $2c, $81, $33, $85, $33, $81, $90, $33, $81, $4b, .lobyte(@env32), .hibyte(@env32)
	.byte $50, $e8, $34, $46, $81
	.byte $41, $20
	.word @song0ref1266
	.byte $00, $bd, $4b, .lobyte(@env19), .hibyte(@env19), $4c
@song0ref1319:
	.byte $2c, $9d, $2a, $8d, $2d, $8d, $2c, $8d, $8e, $2c, $ad, $90, $2d, $8d, $34, $8d, $33, $8d, $2d, $85, $2f, $85, $31, $8d
	.byte $8e, $31, $ad, $90
	.byte $41, $10
	.word @song0ref1319
	.byte $36, $8d, $38, $8d, $8e, $38, $8d, $90, $3c, $8d, $8e, $3c, $8d, $3d, $95, $00, $a5, $bf, $92
	.byte $41, $0c
	.word @song0ref1058
	.byte $28, $81, $1c, $81, $25, $81, $8e, $2c, $85, $2a, $85, $27, $85, $92, $1e, $81, $25, $81, $27, $81, $28, $85, $27, $85
	.byte $00, $95, $44, $00
@song0ch3:
	.byte $bf, $9f, $80, $1f, $89, $1f, $89, $84, $14, $14, $14, $14
@song0ref1413:
	.byte $86
@song0ref1414:
	.byte $1f, $00, $1f, $00, $84, $14, $00, $86, $1f, $00, $1f, $00, $1f, $00, $84, $14, $00, $86, $1f, $00, $1f, $00, $1f, $00
	.byte $84, $14, $00, $86, $1f, $00, $1f, $1f, $1f, $1f, $84, $14, $86, $1f, $1f, $1f
	.byte $41, $20
	.word @song0ref1414
	.byte $41, $20
	.word @song0ref1414
	.byte $41, $20
	.word @song0ref1414
	.byte $41, $19
	.word @song0ref1414
	.byte $00, $1f, $00, $84, $14, $00, $83
	.byte $41, $19
	.word @song0ref1413
	.byte $00, $1f, $00, $84, $14, $00, $83
	.byte $41, $19
	.word @song0ref1413
	.byte $00, $1f, $00, $84, $14, $00, $83
	.byte $41, $19
	.word @song0ref1413
	.byte $00, $1f, $00, $84, $14, $00, $83, $96, $2e, $8d, $80
@song0ref1507:
	.byte $28, $81, $00, $81, $28, $81, $00, $81, $28, $81, $00, $81
	.byte $41, $0c
	.word @song0ref1507
	.byte $41, $0c
	.word @song0ref1507
	.byte $41, $0c
	.word @song0ref1507
	.byte $41, $0c
	.word @song0ref1507
	.byte $41, $0c
	.word @song0ref1507
	.byte $41, $0c
	.word @song0ref1507
	.byte $41, $0c
	.word @song0ref1507
	.byte $41, $0c
	.word @song0ref1507
	.byte $41, $0c
	.word @song0ref1507
@song0ref1546:
	.byte $1f, $00, $1f, $00, $82, $0d, $81, $80, $1f, $00, $1f, $00, $1f, $00, $82, $0d, $81, $80, $1f, $00
	.byte $41, $10
	.word @song0ref1546
	.byte $41, $10
	.word @song0ref1546
	.byte $41, $10
	.word @song0ref1546
	.byte $41, $10
	.word @song0ref1546
	.byte $41, $10
	.word @song0ref1546
	.byte $41, $10
	.word @song0ref1546
	.byte $1f, $00, $1f, $00, $82, $0d, $81, $80, $1f, $1f, $1f, $1f, $1f, $1f, $1f, $1f, $1f, $1f
	.byte $41, $10
	.word @song0ref1546
	.byte $41, $10
	.word @song0ref1546
	.byte $41, $10
	.word @song0ref1546
	.byte $41, $10
	.word @song0ref1546
	.byte $41, $10
	.word @song0ref1546
	.byte $41, $10
	.word @song0ref1546
	.byte $41, $10
	.word @song0ref1546
	.byte $41, $10
	.word @song0ref1546
	.byte $41, $10
	.word @song0ref1546
	.byte $41, $10
	.word @song0ref1546
	.byte $41, $10
	.word @song0ref1546
	.byte $41, $10
	.word @song0ref1546
	.byte $41, $10
	.word @song0ref1546
	.byte $41, $10
	.word @song0ref1546
	.byte $41, $10
	.word @song0ref1546
	.byte $41, $10
	.word @song0ref1546
	.byte $96, $1d, $81, $00, $1d, $81, $00, $1d, $81, $00, $1d, $81, $00, $1d, $81, $00, $1d, $8c, $16, $16, $16, $16, $16, $16
	.byte $16, $16, $96, $1d, $85, $8c, $16, $00, $83
@song0ref1683:
	.byte $16, $79
@song0ref1685:
	.byte $80, $1d, $1d, $1d, $7f, $82, $0d, $81, $79, $80, $1d, $1d, $7f, $8c, $16, $79, $80, $1d, $1d, $1d, $7f, $82, $0d, $81
	.byte $79, $80, $1d, $1d, $7f, $8c
	.byte $41, $10
	.word @song0ref1683
	.byte $41, $10
	.word @song0ref1546
	.byte $41, $10
	.word @song0ref1546
	.byte $8c, $16
	.byte $41, $0f
	.word @song0ref1685
	.byte $7f, $8c
	.byte $41, $10
	.word @song0ref1683
	.byte $41, $10
	.word @song0ref1546
	.byte $41, $10
	.word @song0ref1546
	.byte $8c, $16
	.byte $41, $0f
	.word @song0ref1685
	.byte $7f, $8c
	.byte $41, $10
	.word @song0ref1683
	.byte $41, $10
	.word @song0ref1546
	.byte $41, $10
	.word @song0ref1546
	.byte $8c, $16
	.byte $41, $0f
	.word @song0ref1685
	.byte $7f, $8c
	.byte $41, $10
	.word @song0ref1683
	.byte $82
	.byte $41, $11
	.word @song0ref1110
	.byte $00, $0d, $00, $0d, $00, $0d, $00, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $0d, $96, $1d, $ad, $00, $8d, $bf, $bf, $bf, $1d
	.byte $95, $44, $00
@song0ch4:
	.byte $bf, $ab, $19, $89, $19, $19, $19, $19
@song0ref1806:
	.byte $05, $00, $10, $81, $1c, $81, $10, $81, $05, $00, $10, $81, $1c, $81, $10, $81, $05, $00, $10, $81, $1c, $81, $10, $81
	.byte $10, $10, $10, $10, $1c, $10, $10, $10, $0b, $00, $0f, $81, $1c, $81, $0f, $81, $0b, $00, $0f, $81, $1c, $81, $0f, $81
	.byte $0b, $00, $0f, $81, $1c, $81, $0f, $81, $0f, $0f, $0f, $0f, $1c, $0f, $0f, $0f
	.byte $41, $40
	.word @song0ref1806
	.byte $04, $00, $07, $81, $1c, $81, $07, $81, $04, $00, $07, $81, $1c, $81, $07, $81, $04, $00, $07, $81, $1c, $81, $07, $81
	.byte $07, $07, $07, $07, $1c, $07, $07, $07, $0d, $81, $11, $81, $1c, $81, $11, $81, $0d, $81, $11, $81, $1c, $81, $11, $81
	.byte $0d, $81, $11, $81, $1c, $81, $11, $81, $11, $11, $11, $11, $1c, $11, $11, $11, $0c, $00, $02, $81, $1c, $81, $02, $81
	.byte $0c, $00, $02, $81, $1c, $81, $02, $81, $0c, $00, $02, $81, $1c, $81, $02, $81, $02, $02, $02, $02, $1c, $02, $02, $02
	.byte $19, $81, $06, $81, $1c, $81, $06, $81, $19, $81, $06, $81, $1c, $81, $06, $81, $19, $81, $06, $81, $02, $16, $10, $17
	.byte $08, $10, $02, $17, $10, $02, $17, $02, $19, $81, $09
@song0ref2004:
	.byte $81, $19, $81, $09, $81, $19, $81, $09, $81, $19, $81
@song0ref2015:
	.byte $09, $81, $19, $81, $01, $81, $19, $81, $01, $81, $19, $81, $11, $81, $19, $81, $11, $81, $19, $81, $02, $81, $19, $81
	.byte $02, $81, $19, $81, $02, $81, $19, $81, $02, $81, $19, $81, $10, $81, $19, $81, $10, $81, $19, $81, $07, $81, $19, $81
	.byte $07
	.byte $41, $0f
	.word @song0ref2004
	.byte $41, $31
	.word @song0ref2015
	.byte $81, $19, $81, $09, $81, $1c, $81, $09
@song0ref2078:
	.byte $81, $19, $81, $09, $81, $1c, $81, $09, $81, $19, $81, $01, $81, $1c, $81, $01, $81, $19, $81, $11, $81, $1c, $81, $11
	.byte $81, $19, $81, $02, $81, $1c, $81, $02, $81, $19, $81, $02, $81, $1c, $81, $02, $81, $19, $81, $10, $81, $1c, $81, $10
	.byte $81, $19, $81, $07, $81, $1c, $81, $07, $81, $19, $07, $81, $07, $1c, $07, $81, $07, $19, $07, $07, $81, $1c, $07, $07
	.byte $81, $19, $17, $17, $81, $1c, $17, $02, $81, $19, $02, $02, $81, $1c, $02, $02, $81, $19, $06, $06, $81, $1c, $06, $06
	.byte $81, $19, $06, $06, $81, $1c, $06, $06, $81, $19, $0d, $0d, $81, $1c, $0d, $0d, $07, $19, $07, $07, $81, $1c, $07, $07
	.byte $81, $19, $81
@song0ref2201:
	.byte $18, $81, $1c, $81, $18, $81, $19, $81, $18, $81, $1c, $81, $18
	.byte $41, $13
	.word @song0ref2078
@song0ref2217:
	.byte $10, $81, $1c, $81, $10, $81, $19, $81, $10, $81, $1c, $81, $10, $81, $19, $81, $08, $81, $1c, $81, $08, $81, $19, $81
	.byte $17, $81, $1c, $81, $17, $81, $19, $81, $17, $81, $1c, $81, $17, $81, $19, $81, $17, $81, $1c, $81, $17, $81, $19, $81
	.byte $15, $81, $1c, $81, $15, $81, $19, $81, $0e, $81, $1c, $81, $0e, $81, $19, $81
	.byte $41, $20
	.word @song0ref2217
	.byte $41, $0d
	.word @song0ref2201
	.byte $41, $13
	.word @song0ref2078
	.byte $41, $40
	.word @song0ref2217
	.byte $41, $1e
	.word @song0ref2217
	.byte $17, $81, $00, $16, $81, $00, $0d, $81, $00, $05, $81, $00, $14, $81, $00, $19, $19, $19, $19, $19, $19, $19, $19, $19
	.byte $1c, $85, $00, $85, $19, $81
@song0ref2326:
	.byte $07, $81, $1c, $81, $07, $81, $19, $81, $07, $81, $1c, $81, $07, $81, $19, $81
	.byte $41, $10
	.word @song0ref2217
	.byte $41, $10
	.word @song0ref2326
	.byte $41, $10
	.word @song0ref2326
@song0ref2351:
	.byte $11, $81, $1c, $81, $11, $81, $19, $81, $11, $81, $1c, $81, $11, $81, $19, $81
	.byte $41, $10
	.word @song0ref2217
	.byte $41, $10
	.word @song0ref2326
	.byte $41, $10
	.word @song0ref2326
	.byte $41, $10
	.word @song0ref2326
	.byte $41, $10
	.word @song0ref2217
	.byte $41, $10
	.word @song0ref2326
	.byte $41, $10
	.word @song0ref2326
	.byte $41, $10
	.word @song0ref2351
	.byte $41, $0e
	.word @song0ref2217
	.byte $1c, $81, $02, $81, $1c, $81, $02, $81, $1c, $81, $02, $81, $1c, $81, $02, $81, $1c, $08, $1c, $08, $1c, $08, $1c, $08
	.byte $1c, $1c, $1c, $1c, $1c, $1c, $1c, $1c, $00, $95, $04, $89, $13, $89, $0a, $8d, $00, $89, $04, $81, $0c, $81, $06, $81
	.byte $0d, $85, $0a, $81, $00, $81, $0a, $85, $13, $85, $0e, $85, $0c, $89, $13, $89, $0a, $89, $0c, $89, $13, $85, $0a, $85
	.byte $00, $8d, $0a, $81, $04, $81, $06, $81, $0d, $89, $07, $81, $17, $81, $02, $85, $17, $85, $07, $95, $44, $00
